### PR TITLE
added markdown badges

### LINKED ISSUE #5: #3 Add relevant Markdown Badges for the project in Readme
What are Markdown Badges? Check [here](https://github.com/Ileriayo/markdown-badges)

Refer to [this](https://github.com/PatilShreyas/NotyKT) repository for a sample project with good markdown badges.

Add relevant markdown badges to this project, add a maximum of 2 relevant badges per issue.

### PR DESCRIPTION
**Pull request by priyanshuborole**
**Description** 📜
Added license, star, fork markdown badges in the Readme file.
Fixes #5 

**Domain of Contribution**📊
⬛Documentation

**Checklist** ✅
⬛ I'm GSSOC'22 contributor 

**Changes Screenshot**📸
badges images

### CODE REVIEW

**Comment by SB2318** [comment]
@priyanshuborole Mention the issue number which you fixed

**Comment by priyanshuborole** [comment]
@SB2318 updated.

**Review by SB2318 — APPROVED** [review]
@fin1te will check later.

**Review by fin1te — CHANGES_REQUESTED** [review]
Comment out the License badge, as we haven't added any license yet, will de-comment it later when we add a license to this project later on.

Just comment the license badge, rest all is fine.

**Comment by fin1te** [comment]
@priyanshuborole check out the requested changes, let me know when you're done with it.

**Review by fin1te — COMMENTED** [review]
Looks good now, I've made the changes myself, commented out the license badge and resolved the conflicts this PR had with Issue #8, I think it's good to merge now.

**Comment by priyanshuborole** [comment]
Thanks @fin1te, so no need to change it now right?

**Pull request merged**
