### PR TITLE
Changed the statusBar color

### LINKED ISSUE #1: Change Status Bar color for all activities
Currently, all Fragments and Activities have the default blue status bar, change it to a colour more suitable with the app's user interface (preferably some shade of grey) as well as figure out how to change the icon colour to a dark shade.

**NOTE:** 
- Needs to be Implemented in all activities.
- If you want to try to solve this issue, leave a comment asking me to assign you this issue and I'll assign it to you, once you've been assigned, you can start working on the Implementation.

### PR DESCRIPTION
**Pull request by Pranjali-49**
Fix #1 

- Changed the statusBar colour.
- Changed the Icons to a dark shade.

Here are screenshots of the changes I've made.

WhatsApp Image 2022-03-05 at 11 02 32 AM

WhatsApp Image 2022-03-05 at 11 00 30 AM

### CODE REVIEW

**Comment by Pranjali-49** [comment]
Hey @fin1te, Please review and merge my PR!

**Review by fin1te — COMMENTED** [review]
Reviewing changes will revert by EoD today.

**Review by fin1te — COMMENTED** [review]
There are some issues with this commit that I noted :

- Gradle Plugin level was lowered from `7.1.0` to `7.0.3`
- Module-level Gradle's Plugin was changed from `androidx.navigation.safeargs.kotlin` to `androidx.navigation.safeargs` 
- Due to the last point you were not able to pass the "id" as parameter in the NavDirection, due to which I believe you removed "id" passed as parameter in `HomeFragment.kt`

I've fixed all the problems with your code and created a new commit on your fork, will check again and resolve conflicts before merging the PR.

**Comment by fin1te** [comment]
@Pranjali-49 

> There are some issues with this commit that I noted :
> 
> * Gradle Plugin level was lowered from `7.1.0` to `7.0.3`
> * Module-level Gradle's Plugin was changed from `androidx.navigation.safeargs.kotlin` to `androidx.navigation.safeargs`
> * Due to the last point you were not able to pass the "id" as parameter in the NavDirection, due to which I believe you removed "id" passed as parameter in `HomeFragment.kt`
> 
> I've fixed all the problems with your code and created a new commit on your fork, will check again and resolve conflicts before merging the PR.

**Pull request merged**
