### PR TITLE
Added TrackDetailActivity

### LINKED ISSUE #26: Remove the TrackDetailFragment and replace its implementation with TrackDetailActivity
### Feature description

Remove the `TrackDetailFragment` and it's XML and replace it's implementation with a new `TrackDetailActivity` (Similar to the `EventDetailActivity` in `HomeFragment`)

For any clarification ping me on Discord @fin1te 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Vibhuti2002**
fixed: #26 
Removed TrackDetailFragment and added TrackDetailActivity

### CODE REVIEW

**Review by fin1te — CHANGES_REQUESTED** [review]
Hey, there are conflicts with this PR, try to resolve this conflict (conflict has raised as your origin is 1 commit behind the upstream (main project)).

Try to solve the conflict, if it gets too complicated simply fetch and update your origin fork with the project and then create a new commit, this will also resolve the conflict.

Do by either of the two ways, If you have any issues / confusion ping me on Discord, will reply by 8pm.

**Comment by Vibhuti2002** [comment]
Done @fin1te

**Review by fin1te — COMMENTED** [review]
There's a couple of bugs, will fix them myself and then merge.

**Review by fin1te — COMMENTED** [review]
Fixed, works as intended now, merging.
Good work @Vibhuti2002! :D

**Pull request merged**
