### PR TITLE
Fixed #51: Notify the user whenever there are any new upcoming events.

### LINKED ISSUE #51: Feature: Notify the user whenever there are any new upcoming events.
### Feature description

You need to show a notification to the user whenever new upcoming event is added. 
Notification message something like this..
"New event is coming...Check it out.." or something else.

Prerequisite knowledge: LiveData

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by MohitGupta121**
Fixed #51 
Notify the user whenever there are any new upcoming events.

In this I implemented FCM in Android App, Now for automation, we have to create Cloud Function in Firebase.

### CODE REVIEW

**Comment by MohitGupta121** [comment]
@fin1te can you please review this Pr I integrated FCM, Now we can send notifications manually or Automatically through Firebase cloud messaging. for issue #51

**Comment by SB2318** [comment]
@fin1te please review this. This is an important issue.

**Comment by fin1te** [comment]
> @fin1te please review this. This is an important issue.

Already on it, sitting with @MohitGupta121 and reviewing the PR right now :D

**Comment by SB2318** [comment]
Okay, Okay, actually currently I am not active. 😅

**Review by fin1te — CHANGES_REQUESTED** [review]
Add your gradle wrapper file to fix the build issue we're having here.

**Review by fin1te — APPROVED** [review]

**Comment by MohitGupta121** [comment]
> Add your gradle wrapper file to fix the build issue we're having here.
 
Done Bhaiya Now check

**Pull request merged**
