### PR TITLE
Fix #64: Add some more tracks.

### LINKED ISSUE #64: Feature: Add  some more tracks.
### Feature description

Guys this issue is little bit interesting.
You have to add some more tracks (some more CardView) with relevant Images and text. 
app_dev

### **Tracks name:**

1. Cloud
2. AR/VR
3. Graphic Design

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by MohitGupta121**
Fix #64 Feature: Add some more tracks.

Below is the Demo Video for Implementation:-

https://user-images.githubusercontent.com/76530270/161730210-c31853e6-e782-447a-98a8-853a63d7d42e.mp4

### CODE REVIEW

**Comment by MohitGupta121** [comment]
@fin1te @SB2318 can u please review this PR for #64 

And also can you please add Labels according to GSSOC'22

**Comment by MohitGupta121** [comment]
@SB2318 can u add labels also in this PR.

**Comment by SB2318** [comment]
Sorry, I can't. Because label is added only when this PR is accepted.

**Comment by MohitGupta121** [comment]
> Sorry, I can't. Because label is added only when this PR is accepted.

Oo Okay no problem.

**Review by fin1te — COMMENTED** [review]
Looks good, checked and merged the PR.

**Pull request merged**
