### PR TITLE
issue #69 solved

### PR DESCRIPTION
**Pull request by sdcode001**

### CODE REVIEW

**Comment by sdcode001** [comment]
@fin1te @SB2318 now its alright

**Review by SB2318 — CHANGES_REQUESTED** [review]
See, If you implement it as a child activity, when you click on the up button, then it will navigate into MainActivity, but GDSC fragment will shown (as it is the start destination of our nav graph.) But we have to go back into about fragment.  So, remove the 
android:parentActivity from manifest file. And 
As of now, just create an intent in onItemClick() method. Use

requireContext().startActivity(intent)
To reach in track details activity.

**Comment by SB2318** [comment]
If you faces any problem with this, contact us on discord. But, Currently I am busy, I will discuss it in the evening.

**Comment by SB2318** [comment]
@sdcode001 
### Remove:
parent_activity

### And
action_bar

**Comment by sdcode001** [comment]
https://user-images.githubusercontent.com/92887905/163167623-33b6506b-30fc-40a1-afc5-f1ecd5ffd4ca.mp4

**Comment by sdcode001** [comment]
but see @SB2318 it works totally fine

**Pull request closed without merging**
