### PR TITLE
issue#69 solved

### PR DESCRIPTION
**Pull request by sdcode001**
Screenshot_20220409_012216

### CODE REVIEW

**Comment by sdcode001** [comment]
@SB2318 @fin1te ....review this PR

**Review by SB2318 — APPROVED** [review]
This is a level 1 issue. You could do this in a nutshell just by using the action bar. But it is also okay.👍
Looks good to me.

**Comment by SB2318** [comment]
@fin1te please make a decision on this PR.

**Review by fin1te — CHANGES_REQUESTED** [review]
Hey, please use an ActionBar instead of a toolbar is @SB2318 suggested, because then we can implement backward navigation.

**Comment by sdcode001** [comment]
Screenshot_20220413_005518

**Comment by sdcode001** [comment]
@fin1te implemented backward navigation using action bar

**Comment by SB2318** [comment]
@sdcode001 I am not saying you are wrong. But why are you do the same mistake again and again. @fin1te is busy, it is not always possible to merge the PR. Please understand.

**Comment by SB2318** [comment]
Come in the discord VC at 10:30 am. I will explain you the matter. But this is your last chance.

**Comment by SB2318** [comment]
@sdcode001 close your current PR, and please take respective actions for making a fresh PR.(I hope you understand the matter.)

Complete it within today, Otherwise you will unassigned from the issue.

**Pull request closed without merging**
