### PR TITLE
added relevant markdown badges

### LINKED ISSUE #3: #1 Add relevant Markdown Badges for the project in Readme
What are Markdown Badges? Check [here](https://github.com/Ileriayo/markdown-badges)

Refer to [this](https://github.com/PatilShreyas/NotyKT) repository for a sample project with good markdown badges.

Add relevant markdown badges to this project, add a maximum of 2 relevant badges per issue.

### PR DESCRIPTION
**Pull request by itsAftabAlam**
I hope this fixes #3 , please review

### CODE REVIEW

**Review by SB2318 — APPROVED** [review]

**Review by SB2318 — CHANGES_REQUESTED** [review]
You did well. But add some more relevant badges in the tech stack area like **MVVM**, **Android,** read the readme file and Think about what tech stack you can give.

**Comment by itsAftabAlam** [comment]
ok i will work on it, actually it was written in the issue to use maximum of 2 badges that's why i did not added more badges

**Review by SB2318 — APPROVED** [review]
@fin1te will check later.

**Review by fin1te — COMMENTED** [review]
I've removed the Android Markdown badge as just the Android Studio badge seems enough, will be merging this PR now.

**Pull request merged**
