### PR TITLE
added contributor badge

### LINKED ISSUE #32: Add Contribution badges in the Readme file of this Project.
### Description

Add Contribution badges in the Readme file of this Project.

Refer to [this](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/main/README.md#thanks-to-all-the-contributors-%EF%B8%8F) repository for a sample readme file with Contribution badges.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by lalit-patel**
**Description**
Add Contribution badges in the Readme file of this Project.
Fixes #32

**Screenshot**
Screenshot (1)

### CODE REVIEW

**Review by SB2318 — CHANGES_REQUESTED** [review]
@lalit-patel please take some time, think about how can you make it different. You can do it.😇 Otherwise we will give you some hints. Because it is a level 1 issue.

**Review by fin1te — COMMENTED** [review]
Hi @lalit-patel, first of all, congratulations on your first ever Pull Request! <3

Your PR resolves the Issue, I'm just adding a little bit of formatting to your PR to make it better, you can click on the commit below this comment and see what changes I've made to your PR.
If you have any doubts feel free to ping me / any other contributor or Mentors on GSSoC's Discord Server! :D

Good luck for your future PRs! :)

**Review by fin1te — COMMENTED** [review]
@lalit-patel Click above and check out the changes

**Comment by lalit-patel** [comment]
Thanks @fin1te , Sure will checkout the changes

**Pull request merged**
